name: bootcamp_project_02
description: GitHub client.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.3.0"

dependencies:
  flutter:
    sdk: flutter
  oauth2: ^2.0.0
  flutter_secure_storage: ^4.2.1
  dartz: ^0.10.1-nullsafety.2
  dio: ^4.0.0
  flutter_hooks: ^0.16.0
  hooks_riverpod:
    git:
      url: https://github.com/rrousselGit/river_pod.git
      ref: 147be70df096015af0633456a951d8f2f9c66dc9
      path: packages/hooks_riverpod
  freezed_annotation: ^0.14.3
  webview_flutter: ^2.8.0
  flash: ^2.0.5
  material_design_icons_flutter: ^5.0.6996
  json_annotation: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.0
  freezed: ^0.14.5
  auto_route_generator: ^4.2.0
  lint: ^1.5.3
  json_serializable: ^6.1.6
  analyzer: any

dependency_overrides:
  build_runner: any
  flutter_riverpod:
    git:
      url: https://github.com/rrousselGit/river_pod.git
      ref: 147be70df096015af0633456a951d8f2f9c66dc9
      path: packages/flutter_riverpod
  riverpod:
    git:
      url: https://github.com/rrousselGit/river_pod.git
      ref: 147be70df096015af0633456a951d8f2f9c66dc9
      path: packages/riverpod

flutter:
  uses-material-design: true
